// Generated by CoffeeScript 1.8.0
(function() {
  import hafemInitializer from './initializers/hafem';
  Ember.Application.initializer(hafemInitializer);

  Ember.libraries.register("Hafem", "0.0.1");

  export default '';

}).call(this);

//# sourceMappingURL=hafem.js.map
