// Generated by CoffeeScript 1.8.0
(function() {
  import HafemCoreEngine from '../utils/hafem/directives/famous/core/Engine';
  import HafemCoreSurface from '../utils/hafem/directives/famous/core/Surface';
  import HafemViewsGridLayout from '../utils/hafem/directives/famous/views/GridLayout';
  var View;

  View = Ember.View.extend({
    didInsertElement: function() {
      var Engine, GridLayout, Surface, grid, i, mainContext, surfaces, useHafem;
      useHafem = true;
      Engine = useHafem ? HafemCoreEngine : famous.core.Engine;
      Surface = useHafem ? HafemCoreSurface : famous.core.Surface;
      GridLayout = useHafem ? HafemViewsGridLayout : famous.views.GridLayout;
      mainContext = Engine.createContext();
      grid = new GridLayout({
        dimensions: [4, 1]
      });
      surfaces = [];
      grid.sequenceFrom(surfaces);
      i = 0;
      while (i < 8) {
        surfaces.push(new Surface({
          content: "panel " + (i + 1),
          size: [undefined, undefined],
          properties: {
            backgroundColor: "hsl(" + (i * 360 / 8) + ", 100%, 50%)",
            color: "#404040",
            lineHeight: "200px",
            textAlign: "center"
          }
        }));
        i++;
      }
      return mainContext.add(grid);
    }
  });

  export default View;

}).call(this);

//# sourceMappingURL=fagridlayout.js.map
