// Generated by CoffeeScript 1.8.0
(function() {
  import HafemCoreEngine from '../utils/hafem/directives/famous/core/Engine';
  import HafemCoreSurface from '../utils/hafem/directives/famous/core/Surface';
  import HafemViewsScrollview from '../utils/hafem/directives/famous/views/Scrollview';
  var View;

  View = Ember.View.extend({
    didInsertElement: function() {
      var Engine, Scrollview, Surface, i, mainContext, scrollview, self, temp, useHafem, _results;
      useHafem = true;
      Engine = useHafem ? HafemCoreEngine : famous.core.Engine;
      Surface = useHafem ? HafemCoreSurface : famous.core.Surface;
      Scrollview = useHafem ? HafemViewsScrollview : famous.views.Scrollview;
      self = this;
      this.set('surfaces', []);
      mainContext = Engine.createContext($('#test-context')[0]);
      scrollview = new Scrollview();
      scrollview.sequenceFrom(this.get('surfaces'));
      mainContext.add(scrollview);
      i = 0;
      _results = [];
      while (i < 40) {
        temp = new Surface({
          content: "Surface: " + (i + 1),
          size: [undefined, 200],
          properties: {
            backgroundColor: "hsl(" + (i * 360 / 40) + ", 100%, 50%)"
          }
        });
        temp.pipe(scrollview);
        self.get('surfaces').push(temp);
        _results.push(i++);
      }
      return _results;
    }
  });

  export default View;

}).call(this);

//# sourceMappingURL=fascrollview.js.map
