// Generated by CoffeeScript 1.8.0
(function() {
  import HafemCoreEngine from '../utils/hafem/directives/famous/core/Engine';
  import HafemCoreSurface from '../utils/hafem/directives/famous/core/Surface';
  import HafemViewsSequentialLayout from '../utils/hafem/directives/famous/views/SequentialLayout';
  var View;

  View = Ember.View.extend({
    didInsertElement: function() {
      var Engine, SequentialLayout, Surface, i, mainContext, sequentialLayout, surfaces, useHafem;
      useHafem = true;
      Engine = useHafem ? HafemCoreEngine : famous.core.Engine;
      Surface = useHafem ? HafemCoreSurface : famous.core.Surface;
      SequentialLayout = useHafem ? HafemViewsSequentialLayout : famous.views.SequentialLayout;
      mainContext = Engine.createContext();
      sequentialLayout = new SequentialLayout();
      surfaces = [];
      sequentialLayout.sequenceFrom(surfaces);
      i = 0;
      while (i < 10) {
        surfaces.push(new Surface({
          size: [undefined, 50],
          properties: {
            backgroundColor: "hsl(" + (i * 360 / 10) + ", 100%, 50%)"
          }
        }));
        i++;
      }
      return mainContext.add(sequentialLayout);
    }
  });

  export default View;

}).call(this);

//# sourceMappingURL=fasequentiallayout.js.map
