// Generated by CoffeeScript 1.8.0
(function() {
  var HafemViewsFlexibleLayout;

  HafemViewsFlexibleLayout = function(options) {
    var FlexibleLayout;
    FlexibleLayout = Famous.Views.FlexibleLayout;
    return new FlexibleLayout(options);
  };

  export default HafemViewsFlexibleLayout;

}).call(this);

//# sourceMappingURL=FlexibleLayout.js.map
