// Generated by CoffeeScript 1.8.0
(function() {
  var HafemViewsGridLayout;

  HafemViewsGridLayout = function(options) {
    var GridLayout;
    GridLayout = Famous.Views.GridLayout;
    return new GridLayout(options);
  };

  export default HafemViewsGridLayout;

}).call(this);

//# sourceMappingURL=GridLayout.js.map
