// Generated by CoffeeScript 1.8.0
(function() {
  var HafemViewsHeaderFooterLayout;

  HafemViewsHeaderFooterLayout = function(options) {
    var HeaderFooterLayout;
    HeaderFooterLayout = Famous.Views.HeaderFooterLayout;
    return new HeaderFooterLayout(options);
  };

  export default HafemViewsHeaderFooterLayout;

}).call(this);

//# sourceMappingURL=HeaderFooterLayout.js.map
