// Generated by CoffeeScript 1.8.0
(function() {
  var HafemViewsScrollview;

  HafemViewsScrollview = function(options) {
    var Scrollview;
    Scrollview = Famous.Views.Scrollview;
    return new Scrollview(options);
  };

  export default HafemViewsScrollview;

}).call(this);

//# sourceMappingURL=Scrollview.js.map
