// Generated by CoffeeScript 1.8.0
(function() {
  var HafemViewsSequentialLayout;

  HafemViewsSequentialLayout = function(options) {
    var SequentialLayout;
    SequentialLayout = Famous.Views.SequentialLayout;
    return new SequentialLayout(options);
  };

  export default HafemViewsSequentialLayout;

}).call(this);

//# sourceMappingURL=SequentialLayout.js.map
