// Generated by CoffeeScript 1.8.0
(function() {
  var HafemTransitionsEasing;

  HafemTransitionsEasing = Famous.Transitions.Easing;

  export default HafemTransitionsEasing;

}).call(this);

//# sourceMappingURL=Easing.js.map
