// Generated by CoffeeScript 1.8.0
(function() {
  import Hafem from '../../../directives/famous';
  var Component;

  Component = Hafem.Component.extend(Ember.ViewTargetActionSupport, {
    classNames: ['famous', 'famous-dom-consumer', 'famous-modifier'],
    tagName: '',
    famous: {
      _type: Ember.A(['famous', 'famous-dom-consumer', 'famous-modifier'])
    },
    'fa-translate-x': null,
    'fa-translate-y': null,
    'fa-translate-z': null,
    'fa-rotate-z': null,
    addTransform: function(transform) {
      var self;
      self = this;
      transform = new Hafem.Famous.Core.Modifier({
        transform: transform
      });
      this.set('fa', this.get('fa').add(transform));
      return this.set('transform', transform);
    },
    willInsertFamous: function() {
      this.set('fa', this.hafem.isolate.get(this).get('fa'));
      this.addTransform(Hafem.Famous.Core.Transform.translate(this.get('fa-translate-x'), this.get('fa-translate-y'), this.get('fa-translate-z')));
      if (this.get('fa-rotate-z')) {
        return this.addTransform(Hafem.Famous.Core.Transform.rotateZ(this.get('fa-rotate-z')));
      }
    }
  });

  export default Component;

}).call(this);

//# sourceMappingURL=modifier.js.map
