// Generated by CoffeeScript 1.8.0
(function() {
  import Hafem from '../../../directives/famous';
  var Component;

  Component = Hafem.Component.extend(Ember.ViewTargetActionSupport, {
    classNames: ['famous', 'famous-dom-consumer', 'famous-surface'],
    famous: {
      _type: Ember.A(['famous', 'famous-dom-consumer', 'famous-surface'])
    },
    changeSize: (function() {
      return this.get('fa').setSize([this.get('fa-width'), this.get('fa-height')]);
    }).observes('fa-width', 'fa-height'),
    willInsertFamous: function() {
      var fa, self;
      self = this;
      fa = new Hafem.Famous.Core.Surface({
        size: [this.get('fa-width'), this.get('fa-height')],
        target: self.$()[0],
        content: self.$().html(),
        properties: {
          background: self.get('fa-color')
        }
      });
      this.set('fa', fa);
      return this.hafem.isolate.get(this).addTo(fa);
    },
    click: function() {
      return this.triggerAction(this);
    }
  });

  export default Component;

}).call(this);

//# sourceMappingURL=surface.js.map
