// Generated by CoffeeScript 1.8.0
(function() {
  import Hafem from '../../../directives/famous';
  var Component;

  Component = Hafem.Component.extend({
    classNames: ['famous', 'famous-dom-consumer', 'famous-view'],
    famous: {
      _type: Ember.A(['famous', 'famous-dom-consumer', 'famous-view'])
    },
    willInsertFamous: function() {
      var fa, self;
      self = this;
      fa = new Hafem.Famous.Core.View();
      this.set('fa', fa);
      return this.hafem.isolate.get(this).addTo(fa);
    }
  });

  export default Component;

}).call(this);

//# sourceMappingURL=view.js.map
