// Generated by CoffeeScript 1.8.0
(function() {
  import Hafem from '../../../directives/famous';
  var Component;

  Component = Hafem.LayoutComponent.extend({
    classNames: ['famous-context', 'famous-views-flexible-layout'],
    famous: {
      _type: Ember.A(['famous', 'famous-dom-consumer', 'famous-flexibleLayout'])
    },
    'fa-ratio': '[1]',
    ratios: function() {
      return eval(this.get('fa-ratio'));
    },
    properties: function() {
      return {
        ratios: this.ratios(),
        direction: 0
      };
    },
    clazz: 'FlexibleLayout'
  });

  export default Component;

}).call(this);

//# sourceMappingURL=flexible-layout.js.map
