// Generated by CoffeeScript 1.8.0
(function() {
  import Hafem from '../../../directives/famous';
  var Component;

  Component = Hafem.LayoutComponent.extend({
    classNames: ['famous-context', 'famous-views-sequential-layout'],
    famous: {
      _type: Ember.A(['famous', 'famous-dom-consumer', 'famous-sequentialLayout'])
    },
    'fa-direction': 0,
    direction: function() {
      return this.get('fa-direction');
    },
    properties: function() {
      return {
        direction: this.direction()
      };
    },
    clazz: 'SequentialLayout'
  });

  export default Component;

}).call(this);

//# sourceMappingURL=sequential-layout.js.map
