// Generated by CoffeeScript 1.8.0
(function() {
  import Hafem from '../../../../directives/famous';
  var Component;

  Component = Hafem.HflComponent.extend({
    classNames: ['famous-context', 'famous-views-header-footer-layout-content'],
    famous: {
      _type: Ember.A(['famous', 'famous-dom-consumer', 'famous-header-footer-layout-content'])
    },
    targetName: 'content',
    willInsertFamous: function() {}
  });

  export default Component;

}).call(this);

//# sourceMappingURL=content.js.map
