// Generated by CoffeeScript 1.8.0
(function() {
  import Hafem from '../../../../directives/famous';
  var Component;

  Component = Hafem.HflComponent.extend({
    classNames: ['famous-context', 'famous-views-header-footer-layout-footer'],
    famous: {
      _type: Ember.A(['famous', 'famous-dom-consumer', 'famous-header-footer-layout-footer'])
    },
    addTarget: 'footer',
    properties: function() {
      return {
        footerSize: this.height()
      };
    }
  });

  export default Component;

}).call(this);

//# sourceMappingURL=footer.js.map
