// Generated by CoffeeScript 1.8.0
(function() {
  var HafemCoreEngine;

  HafemCoreEngine = Famous.Core.Engine;

  export default HafemCoreEngine;

}).call(this);

//# sourceMappingURL=Engine.js.map
