// Generated by CoffeeScript 1.8.0
(function() {
  var HafemCoreModifier;

  HafemCoreModifier = function(options) {
    var Modifier, self;
    self = this;
    Modifier = Famous.Core.Modifier;
    return new Modifier(options);
  };

  export default HafemCoreModifier;

}).call(this);

//# sourceMappingURL=Modifier.js.map
