// Generated by CoffeeScript 1.8.0
(function() {
  var HafemCoreSurface;

  HafemCoreSurface = function(options) {
    var Surface, self, surface;
    self = this;
    Surface = Famous.Core.Surface;
    surface = new Surface(options);
    surface.setup = function(allocator) {
      if (options.target) {
        Surface.prototype.elementType = options.target;
        allocator.allocate = function(type) {
          var result;
          result = type;
          this.nodeCount++;
          return result;
        };
      } else {
        Surface.prototype.elementType = options.elementType ? options.elementType : Surface.prototype.elementType;
      }
      Surface.prototype.setup.call(this, allocator);
    };
    surface.deploy = function(target) {
      return Surface.prototype.deploy.call(surface, target);
    };
    surface.cleanup = function(allocator) {
      allocator.deallocate = function(type) {};
      return Surface.prototype.cleanup.call(surface, allocator);
    };
    surface.recall = function(target) {};
    return surface;
  };

  export default HafemCoreSurface;

}).call(this);

//# sourceMappingURL=Surface.js.map
