// Generated by CoffeeScript 1.8.0
(function() {
  var HafemCoreTransform;

  HafemCoreTransform = Famous.Core.Transform;

  export default HafemCoreTransform;

}).call(this);

//# sourceMappingURL=Transform.js.map
