// Generated by CoffeeScript 1.8.0
(function() {
  var HafemCoreView;

  HafemCoreView = function(options) {
    var View, self;
    self = this;
    View = Famous.Core.View;
    return new View(options);
  };

  export default HafemCoreView;

}).call(this);

//# sourceMappingURL=View.js.map
